name: HW1 Tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: go mod download

            - name: Running HW1 Tests
              uses: actions/setup-go@v3
              with:
                go-version: 1.20

            - name: PartOne
              run: go test -v ./part-one/uniq

            - name: PartTwo
              run: go test -v ./part-two/calc